#!/bin/bash



if [ "$(df -P -T /backups | tail -n +2 | awk '{print $2}')" != "nfs" ] ; then
	echo les systeme de fichier n\'était pas monté\! montage\!
	mount /backups
fi

if [ "$(df -P -T /backups | tail -n +2 | awk '{print $2}')" != "nfs" ] ; then
        echo le systeme de fichier n\'est toujours pas monté\! abandon\!\!\!\!\!\!
	exit 2
fi

MY_DIR=$(dirname $0)

echo --------Debut de sauvegarde--------
echo ----sauvegarde SQL
$MY_DIR/mysqldump 2>&1
echo ----sauvegarde des fichiers
$MY_DIR/filesdump 2>&1
echo ----sauvegarde des certificats
$MY_DIR/certsdump 2>&1
#echo ----sauvegarde munin
#/root/munin_bak 2>&1
echo --------Sauvegarde terminee--------

echo

echo ----------  Nettoyage   -----------
find /backups -depth -xdev -maxdepth 2 -type f -mtime +15 -not -path "*cert*" -delete
echo --------- Fin nettoyage -----------

umount /backups
