#!/bin/bash

BKP_FOLDER=/backups

if ! mountpoint ${BKP_FOLDER} ; then
	echo les systeme de fichier ${BKP_FOLDER} n\'était pas monté\! montage\!
	mount ${BKP_FOLDER}
fi

if ! mountpoint ${BKP_FOLDER} ; then
        echo le systeme de fichier ${BKP_FOLDER} n\'est toujours pas monté\! abandon\!\!\!\!\!\!
	exit 2
fi

MY_DIR=$(dirname $0)

echo --------Debut de sauvegarde--------
echo ----sauvegarde SQL
$MY_DIR/mysqldump 2>&1
echo ----sauvegarde des fichiers
$MY_DIR/filesdump 2>&1
echo ----sauvegarde des certificats
$MY_DIR/certsdump 2>&1
#echo ----sauvegarde munin
#/root/munin_bak 2>&1
echo --------Sauvegarde terminee--------

echo

echo ----------  Nettoyage   -----------
find ${BKP_FOLDER} -depth -xdev -maxdepth 2 -type f -mtime +15 -not -path "*cert*" -delete
echo --------- Fin nettoyage -----------

if ! mountpoint ${BKP_FOLDER} ; then
        umount ${BKP_FOLDER}
	return 0
else
	echo "Mount point ${BKP_FOLDER} was not mounted..."
	return 1
fi
